// Generated by CoffeeScript 1.3.1
(function() {

  _.extend(Backbone.History.prototype, {
    loadUrl: _.wrap(Backbone.History.prototype.loadUrl, function() {
      var argsCalledWith;
      argsCalledWith = Array.prototype.slice.call(arguments, 1);
      router.trigger('route:before', argsCalledWith);
      arguments[0].apply(this, argsCalledWith);
      return router.trigger('route:after', this.fragment);
    })
  });

  _.extend(Backbone.Model.prototype, {
    sync: _.wrap(Backbone.Model.prototype.sync, function() {
      var args;
      args = Array.prototype.slice.call(arguments, 1);
      if (this.storeName) {
        if (args[0] === 'read') {
          if (localStorage[this.storeName]) {
            return args[2].success(localStorage[this.storeName]);
          }
        } else if (args[0] === 'create') {
          return localStorage[this.storeName] = JSON.stringify(this);
        }
      } else {
        return arguments[0].apply(this, args);
      }
    })
  });

}).call(this);
