// Generated by CoffeeScript 1.3.1
(function() {

  BH.Lib.Url = {
    base: function() {
      return 'chrome://history/';
    },
    search: function(text) {
      return "#search/" + text;
    },
    week: function(id) {
      return "#weeks/" + id;
    },
    day: function(weekId, id) {
      return "#weeks/" + weekId + "/days/" + id;
    }
  };

}).call(this);
