// Generated by CoffeeScript 1.3.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

  BH.Views.PageVisitView = (function(_super) {

    __extends(PageVisitView, _super);

    PageVisitView.name = 'PageVisitView';

    function PageVisitView() {
      return PageVisitView.__super__.constructor.apply(this, arguments);
    }

    PageVisitView.prototype.className = 'page_visit_view';

    PageVisitView.prototype.templateId = 'pageVisit';

    PageVisitView.prototype.events = {
      'click .delete_visit': 'deleteClicked'
    };

    PageVisitView.prototype.render = function() {
      this.$el.html(this.template(this.model.toTemplate()));
      return this;
    };

    PageVisitView.prototype.deleteClicked = function(ev) {
      var _this = this;
      ev.preventDefault();
      return this.model.destroy({
        success: function() {
          var method;
          method = _this._isGroupedAndEmpty() ? '_removeGroup' : '_remove';
          return _this[method]();
        }
      });
    };

    PageVisitView.prototype._remove = function() {
      return this.$el.slideUp('fast', function() {
        return $el.remove();
      });
    };

    PageVisitView.prototype._removeGroup = function() {
      return $(this._getGroup()).slideUp('fast', function() {
        return $el.remove();
      });
    };

    PageVisitView.prototype._isGroupedAndEmpty = function() {
      if (this.$el.parents('.expanded').children().length === 1) {
        return true;
      } else {
        return false;
      }
    };

    PageVisitView.prototype._getGroup = function() {
      return this.$el.parents('.grouped_visits_view');
    };

    return PageVisitView;

  })(Backbone.View);

}).call(this);
