// Generated by CoffeeScript 1.3.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

  BH.Views.WeekView = (function(_super) {

    __extends(WeekView, _super);

    WeekView.name = 'WeekView';

    function WeekView() {
      return WeekView.__super__.constructor.apply(this, arguments);
    }

    WeekView.prototype.className = 'week_view';

    WeekView.prototype.templateId = 'week';

    WeekView.prototype.events = {
      'click .delete_all': 'clickedDeleteAll'
    };

    WeekView.prototype.initialize = function() {
      var _this = this;
      WeekView.__super__.initialize.call(this);
      this.model.bind('change:percentages', this.updatePercentages, this);
      this.model.bind('change:count', this.updateWeekStats, this);
      return this.model.get('days').each(function(model) {
        return model.bind('change:count', _this.updateDay, _this);
      });
    };

    WeekView.prototype.render = function(type) {
      this.$el.html(this.template(_.extend(i18n.week(), this.model.toTemplate())));
      return this;
    };

    WeekView.prototype.pageTitle = function() {
      return Helpers.pageTitle(this.model.get('title'));
    };

    WeekView.prototype.updateDay = function(model) {
      return $('.number_of_visits', this._getDayElement(model.id)).text(model.get('count'));
    };

    WeekView.prototype.updateWeekStats = function(model) {
      return this.$('.number_of_visits_all_week').text(model.get('count'));
    };

    WeekView.prototype.updatePercentages = function(percentages) {
      var _this = this;
      return this.model.get('days').each(function(model, i) {
        var percentage;
        percentage = _this.model.get('percentages')[i] + '%';
        return $('.bar', _this._getDayElement(model.id)).css({
          width: percentage
        });
      });
    };

    WeekView.prototype.clickedDeleteAll = function(ev) {
      if ($(ev.target).parent().attr('disabled') !== 'disabled') {
        ev.preventDefault();
        this.promptView = BH.Views.CreatePrompt(chrome.i18n.getMessage('confirm_delete_all_visits', [this.model.get('title')]));
        this.promptView.open();
        return this.promptView.model.on('change', this.deleteAction, this);
      }
    };

    WeekView.prototype.deleteAction = function(prompt) {
      if (prompt.get('action')) {
        if (this.model.get('days')) {
          this.promptView.spin();
          this.model.clear();
          this.promptView.close();
          return this.model.fetch();
        }
      } else {
        return this.promptView.close();
      }
    };

    WeekView.prototype._getDayElement = function(id) {
      return this.$("[data-id=" + id + "]");
    };

    return WeekView;

  })(BH.Views.ViewWithSearch);

}).call(this);
