// Generated by CoffeeScript 1.3.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

  BH.Router = (function(_super) {

    __extends(Router, _super);

    Router.name = 'Router';

    function Router() {
      return Router.__super__.constructor.apply(this, arguments);
    }

    Router.prototype.routes = {
      'settings': 'settings',
      'search/*query': 'search',
      'weeks/:id': 'week',
      'weeks/:weekId/days/:id': 'day'
    };

    Router.prototype.initialize = function() {
      window.settings = new BH.Models.Settings();
      window.version = new BH.Models.Version({
        version: '1.6.0'
      });
      window.appView = this.app = new BH.Views.AppView({
        el: $('.app'),
        model: version,
        collection: new BH.Collections.Weeks([
          {
            date: moment().past(chrome.i18n.getMessage('monday'), 0)
          }, {
            date: moment().past(chrome.i18n.getMessage('monday'), 1)
          }, {
            date: moment().past(chrome.i18n.getMessage('monday'), 2)
          }, {
            date: moment().past(chrome.i18n.getMessage('monday'), 3)
          }, {
            date: moment().past(chrome.i18n.getMessage('monday'), 4)
          }, {
            date: moment().past(chrome.i18n.getMessage('monday'), 5)
          }, {
            date: moment().past(chrome.i18n.getMessage('monday'), 6)
          }, {
            date: moment().past(chrome.i18n.getMessage('monday'), 7)
          }, {
            date: moment().past(chrome.i18n.getMessage('monday'), 8)
          }, {
            date: moment().past(chrome.i18n.getMessage('monday'), 9)
          }
        ])
      }).render();
      window.state = new BH.Models.State({
        route: BH.Lib.Url.week(this.app.collection.at(0).id)
      });
      return this.bind('route:after', function(urlFragment) {
        if (urlFragment.length !== 0) {
          return state.set({
            'route': urlFragment
          });
        }
      });
    };

    Router.prototype.week = function(id) {
      var view;
      this.app.weekSelected(id);
      view = this.app.views.weeks[id];
      view.model.fetch();
      return view.select();
    };

    Router.prototype.day = function(weekId, id) {
      var model, view;
      this.app.weekSelected(weekId);
      view = this.app.views.weeks[weekId];
      view.model.fetch();
      view.select();
      model = view.model.get('days').get(id);
      new BH.Views.DayView({
        model: model,
        weekModel: view.model
      }).open();
      return model.fetch();
    };

    Router.prototype.settings = function() {
      var view;
      view = this.app.views.settings;
      return view.select();
    };

    Router.prototype.search = function(query) {
      var view;
      view = this.app.views.search;
      view.select();
      return view.model.set({
        query: query
      });
    };

    return Router;

  })(Backbone.Router);

}).call(this);
