// Generated by CoffeeScript 1.3.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

  BH.Views.CreditsView = (function(_super) {

    __extends(CreditsView, _super);

    CreditsView.name = 'CreditsView';

    function CreditsView() {
      return CreditsView.__super__.constructor.apply(this, arguments);
    }

    CreditsView.prototype.className = 'credits_view';

    CreditsView.prototype.templateId = 'credits';

    CreditsView.prototype.events = {
      'click .close': 'closeClicked'
    };

    CreditsView.prototype.initialize = function() {
      return this.attachGeneralEvents();
    };

    CreditsView.prototype.render = function() {
      this.$el.html(this.template(i18n.credits()));
      return this;
    };

    CreditsView.prototype.closeClicked = function(ev) {
      ev.preventDefault();
      this.close();
      return BH.router.navigate('#settings');
    };

    CreditsView.prototype.openClicked = function(ev) {
      ev.preventDefault();
      return this.open();
    };

    return CreditsView;

  })(BH.Views.Modal);

}).call(this);
