// Generated by CoffeeScript 1.3.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

  BH.Models.PageVisit = (function(_super) {

    __extends(PageVisit, _super);

    PageVisit.name = 'PageVisit';

    function PageVisit() {
      return PageVisit.__super__.constructor.apply(this, arguments);
    }

    PageVisit.prototype.defaults = {
      title: '(No Title)'
    };

    PageVisit.prototype.initialize = function() {
      if (this.get('title') === '') {
        return this.set({
          title: this.defaults.title
        });
      }
    };

    PageVisit.prototype.sync = function(method, model, options) {
      if (method === 'delete') {
        chrome.history.deleteUrl({
          url: this.get('url')
        });
        return options.success(this);
      }
    };

    PageVisit.prototype.toTemplate = function() {
      var properties;
      properties = this.toJSON();
      properties.cid = this.cid;
      return _.extend(properties, i18n.pageVisit());
    };

    PageVisit.prototype.domain = function() {
      var match;
      match = Helpers.getDomain(this.get('url'));
      if (match === null) {
        return null;
      } else {
        return match[0];
      }
    };

    return PageVisit;

  })(Backbone.Model);

}).call(this);
