// Generated by CoffeeScript 1.3.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

  BH.Models.Prompt = (function(_super) {

    __extends(Prompt, _super);

    Prompt.name = 'Prompt';

    function Prompt() {
      return Prompt.__super__.constructor.apply(this, arguments);
    }

    Prompt.prototype.toTemplate = function() {
      return _.extend(this.toJSON(), i18n.prompt());
    };

    return Prompt;

  })(Backbone.Model);

}).call(this);
