// Generated by CoffeeScript 1.3.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

  BH.Models.Search = (function(_super) {

    __extends(Search, _super);

    Search.name = 'Search';

    function Search() {
      return Search.__super__.constructor.apply(this, arguments);
    }

    Search.prototype.initialize = function() {
      return this.bind('change:query', this.updateTitle, this);
    };

    Search.prototype.toTemplate = function() {
      return this.toJSON();
    };

    Search.prototype.updateTitle = function() {
      var joined, terms;
      terms = this.get('query').split(' ');
      joined = chrome.i18n.getMessage('searching_title') + ' ';
      $.each(terms, function(i) {
        joined += '"' + this + '"';
        if (i !== terms.length - 1) {
          return joined += ' ' + chrome.i18n.getMessage('and') + ' ';
        }
      });
      return this.set({
        title: joined
      });
    };

    return Search;

  })(Backbone.Model);

}).call(this);
