// Generated by CoffeeScript 1.3.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

  BH.Models.State = (function(_super) {

    __extends(State, _super);

    State.name = 'State';

    function State() {
      return State.__super__.constructor.apply(this, arguments);
    }

    State.prototype.storeName = 'state';

    State.prototype.defaults = {
      route: 'filter/0_days_ago'
    };

    State.prototype.initialize = function() {
      return this.bind('change', this.save, this);
    };

    State.prototype.parse = function(data) {
      return this.set(JSON.parse(data));
    };

    return State;

  })(Backbone.Model);

}).call(this);
