// Generated by CoffeeScript 1.3.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

  BH.Models.Version = (function(_super) {

    __extends(Version, _super);

    Version.name = 'Version';

    function Version() {
      return Version.__super__.constructor.apply(this, arguments);
    }

    Version.prototype.initialize = function() {
      return this.set({
        suppress: stringToBool(localStorage[this.suppressKey()])
      });
    };

    Version.prototype.toTemplate = function() {
      return _.extend({
        visibility: this.get('suppress') ? '' : 'show'
      }, i18n.version());
    };

    Version.prototype.key = function() {
      return "versions." + (this.get('version'));
    };

    Version.prototype.setSuppress = function(value) {
      if (value) {
        localStorage[this.suppressKey()] = boolToString(value);
      } else {
        delete localStorage[this.suppressKey()];
      }
      return this.set({
        suppress: value
      });
    };

    Version.prototype.suppressKey = function() {
      return "" + (this.key()) + ".suppress";
    };

    return Version;

  })(Backbone.Model);

}).call(this);
