// Generated by CoffeeScript 1.3.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

  BH.Models.Visit = (function(_super) {

    __extends(Visit, _super);

    Visit.name = 'Visit';

    function Visit() {
      return Visit.__super__.constructor.apply(this, arguments);
    }

    Visit.prototype.defaults = {
      title: '(No Title)'
    };

    Visit.prototype.initialize = function() {
      return this.set(this.get('title') === '' ? {
        title: this.defaults.title
      } : void 0, {
        id: this.cid
      });
    };

    Visit.prototype.sync = function(method, model, options) {
      if (method === 'delete') {
        chrome.history.deleteUrl({
          url: this.get('url')
        });
        return options.success(this);
      }
    };

    Visit.prototype.toTemplate = function() {
      return _.extend(this.toJSON(), i18n.pageVisit());
    };

    Visit.prototype.domain = function() {
      var match;
      match = Helpers.getDomain(this.get('url'));
      if (match === null) {
        return null;
      } else {
        return match[0];
      }
    };

    return Visit;

  })(Backbone.Model);

}).call(this);
