// Generated by CoffeeScript 1.3.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

  BH.Collections.Days = (function(_super) {

    __extends(Days, _super);

    Days.name = 'Days';

    function Days() {
      return Days.__super__.constructor.apply(this, arguments);
    }

    Days.prototype.model = BH.Models.Day;

    Days.prototype.toTemplate = function() {
      var days;
      days = [];
      this.each(function(model) {
        return days.push(model.toTemplate());
      });
      return {
        days: days
      };
    };

    Days.prototype.clear = function() {
      return this.each(function(model) {
        return model.clear();
      });
    };

    return Days;

  })(Backbone.Collection);

}).call(this);
