// Generated by CoffeeScript 1.3.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

  BH.Collections.GroupedVisits = (function(_super) {

    __extends(GroupedVisits, _super);

    GroupedVisits.name = 'GroupedVisits';

    function GroupedVisits() {
      return GroupedVisits.__super__.constructor.apply(this, arguments);
    }

    GroupedVisits.prototype.model = BH.Models.PageVisit;

    GroupedVisits.prototype.toTemplate = function() {
      return _.extend({
        domain: this.at(0).domain(),
        url: this.at(0).get('url')
      }, i18n.groupedVisits());
    };

    GroupedVisits.prototype.destroyAll = function() {
      var _results;
      _results = [];
      while (this.length > 0) {
        if (this.at(0)) {
          _results.push(this.at(0).destroy());
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };

    return GroupedVisits;

  })(Backbone.Collection);

}).call(this);
