// Generated by CoffeeScript 1.3.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

  BH.Collections.PageVisits = (function(_super) {

    __extends(PageVisits, _super);

    PageVisits.name = 'PageVisits';

    function PageVisits() {
      return PageVisits.__super__.constructor.apply(this, arguments);
    }

    PageVisits.prototype.model = BH.Models.PageVisit;

    PageVisits.prototype.destroyAll = function() {
      var _results;
      _results = [];
      while (this.length > 0) {
        if (this.at(0)) {
          _results.push(this.at(0).destroy());
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };

    return PageVisits;

  })(Backbone.Collection);

}).call(this);
