// Generated by CoffeeScript 1.3.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

  BH.Collections.TimeVisits = (function(_super) {

    __extends(TimeVisits, _super);

    TimeVisits.name = 'TimeVisits';

    function TimeVisits() {
      return TimeVisits.__super__.constructor.apply(this, arguments);
    }

    TimeVisits.prototype.model = BH.Models.TimeVisit;

    TimeVisits.prototype.toTemplate = function() {
      var timeVisits;
      timeVisits = {};
      this.each(function(model) {
        return timeVisits.push(model.toTemplate());
      });
      return {
        timeVisits: timeVisits
      };
    };

    TimeVisits.prototype.destroyAll = function() {
      var _results;
      _results = [];
      while (this.length > 0) {
        if (this.at(0)) {
          _results.push(this.at(0).destroy());
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };

    return TimeVisits;

  })(Backbone.Collection);

}).call(this);
