// Generated by CoffeeScript 1.3.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

  BH.Collections.Weeks = (function(_super) {

    __extends(Weeks, _super);

    Weeks.name = 'Weeks';

    function Weeks() {
      return Weeks.__super__.constructor.apply(this, arguments);
    }

    Weeks.prototype.model = BH.Models.Week;

    Weeks.prototype.toTemplate = function() {
      var weeks;
      weeks = [];
      this.each(function(model) {
        return weeks.push(model.toTemplate());
      });
      return {
        weeks: weeks
      };
    };

    return Weeks;

  })(Backbone.Collection);

}).call(this);
